server:
  port: 8888

spring:
  profiles:
    active:
    - native
  cloud:
    config:
      server:
        native:
          search-locations:
          - file://${user.home}/config-repo
#        git:
#          uri: file://${user.home}/config-repo
#          skipSslValidation: true