version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper:3-debian-10
    ports:
    - 2181:2181
    volumes:
    - zookeeper_data:/bitnami
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2-debian-10
    ports:
    - 9093:9093
    volumes:
    - kafka_data:/bitnami
    environment:
    - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
    - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
    - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093
    - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093
    - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
    - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
    - 9100:9000
    environment:
    - KAFKA_BROKERCONNECT=kafka:9092
    - JVM_OPTS=-Xms32M -Xmx64M
    depends_on:
    - kafka
  mq:
    image: ibmcom/mq:latest
    ports:
    - 9443:9443
    - 1414:1414
    environment:
    - LICENSE=accept
    - MQ_QMGR_NAME=QM1
    - MQ_APP_PASSWORD=passw0rd
    volumes:
    - qm1data:/mnt/mqm
    depends_on:
    - kafka    
volumes:
  zookeeper_data: null
  kafka_data: null
  qm1data:
  