version: '3'
services:
  mq:
    image: ibmcom/mq:latest
    ports:
    - 9443:9443
    - 1414:1414
    environment:
    - LICENSE=accept
    - MQ_QMGR_NAME=QM1
    - MQ_APP_PASSWORD=passw0rd
    volumes:
    - qm1data:/mnt/mqm
volumes:
  qm1data:
    